### ISSUE TITLE
Using dyanmic vsif option does not provide proper number of session xml files

### ISSUE THREAD

**Issue by aq-lporter** [jenkinsci/vmanager-plugin#4]
It would be great if there was an option on the vManager Launcher plug-in to include the vManager ID numbers as an _suffix to the default file name of session_runs.xml in either static or dynamic .vsif mode.

As an example: 
Based on the numbers in the ${BUILD_NUM}.${BUILD_ID}.session_launch.output file that gets generated by the plug-in that the resulting session_runs.xml would be session_runs_X.xml and session_runs_Y.xml where (in this example) X and Y are the vManager session numbers generated by the plug-in for that Jenkins j.ob. That way in the Jenkins reporting phase, I would be able to write a wildcard that would catch all of the .xmls generated by that Jenkins job.

**Comment by tyanai** [comment]
Hi aq,

We can try and make in addition to the session_runs.xml, one more session_runs_X.xml per vManager session.  Will make those under an additional directory called junit just to be sure it will not effect any other user.

Will that work for you?

Thanks,

Tal.

**Comment by aq-lporter** [comment]
That should be fine for an experiment. As long as the junit directory is in the same directory as the original session_runs.xml then that should be fine. 

Thanks

Larry

**Comment by tyanai** [comment]
Hi Larry,

I understand you are having more than 1 session artifact for each build. 

Are you intend on reading these xml files from the JUnit plugin?  How will you differentiate between older XML from previous builds that will also be kept?  

Thanks,

Tal.

**Comment by aq-lporter** [comment]
In the example I a currently running on, I have 4 sessions in the file that I have provided to the Dynamic VSIFS of the plug in.

Yes, the plan was to have all of the .xml reports that were generated from the job. 

I was expecting that this would work the same way as it does for other Jenkins jobs.  How does this work now with single session_runs.xml? I thought Jenkins stored this information somewhere since there is a history of pass/fail information in the Test Results Analyzer plug-in.

Thanks

Larry

**Comment by aq-lporter** [comment]
Hi Tal,

I was just talking to someone more versed than me in this and he told me that as a part of the JUnit reporting, that it copies the .xml (and other stuff) to a /u/jenkins area for building of web portal widgets and stuff. So i figure that your solution would use the same flow in that all of the .xmls that are generated will be snapshot in a similar fashion.

Thanks

Larry

**Comment by tyanai** [comment]
Hi Larry,

Got it.  I now see that there was a bug in the way we collect the results into session_runs.xml.  Instead of merging all the runs from all sessions - we only merged the runs from the last session in the list.  

We fixed that, and so from the next update of the Plugin, you will have all the runs aggregated within session_runs.xml already.  I suppose this will address your needs, is it?

Appreciate your feedback,

Thanks,

Tal.

**Comment by aq-lporter** [comment]
Hi Tal,

I didn't realize that was a bug, I thought it was expected behaviour of the plug-in. If the session_runs.xml now aggregates all of the sessions that would fix the issue I was hoping to have addressed.

Thanks

Larry

**Comment by tyanai** [comment]
Version 2.5.9 is now public.

•Added a link within the project page for direct access to the vManager web analysis (post-build action)
•Added a table of sessions within the project's page to track the session's history and give high level overview about the progress (post-build action)
•Added support for vManager HA architecture
•Fix JUnit report to aggregate all runs from all session's that were launched as part of the build (before only the last session's runs were collected).  This is only relevant for build that launches more than one session.
