### ISSUE TITLE
Stopping a Jenkins build does not stop the underlying vManager session

### ISSUE THREAD

**Issue by tudortimi** [jenkinsci/vmanager-plugin#5]
The session was started outside of the plugin and the plugin connected to it afterwards.

**Comment by tyanai** [comment]
Hi Tudor,

Thanks for your feedback.  Indeed, this is not supported today.  We will look into adding this capability.

Thanks,

Tal.

**Comment by tyanai** [comment]
Hi Tudor,

version 3.0.2 now support session suspend in case user interrupt the jenkins job.  There's a new checkbox you must tick in order for this feature to take effect.

Thanks,

Tal.
