### ISSUE TITLE
Use session launcher geometry broken

### ISSUE THREAD

**Issue by bigblondewolf** [jenkinsci/vmanager-plugin#7]
Hi,
The Use session launcher config has strange geometry - it is pushed to the right side of the screen, as shown in the picture.
**Steps to reproduce**
1. Add build step "Cadence vManager Session Launcher".
1. Click the "Use session launcher" radio button.

**Environment**
Tested on both Firefox and Edge, with Jenkins 2.249.3, vAPI plugin v.3.0.7 and 3.1.2

Cheers,
Oggy
![vmgr_session_launcher_misplaced](https://user-images.githubusercontent.com/17025244/100094885-5d2f8480-2e62-11eb-885a-a995b66624ad.png)

**Comment by tyanai** [comment]
Fixed.
