### ISSUE TITLE
vmgr run failure aborts the build

### ISSUE THREAD

**Issue by bigblondewolf** [jenkinsci/vmanager-plugin#8]
I am running vManager with the Session Runner. I pass one vsif.input, which contains multiple vsifs.

The Session Runner options allow to mark the build failed If one or if all runs from the sessions failed (the two empty boxes in the attached image). If I understand correctly this will abort the build, regardless if other sessions are running.

Is it possible to mark the build failed, but not stop the other sessions from the same build? I guess this needs to happen in a post-build action, but didn’t find such an option.

Cheers,
Oggy

![vmgr_session_runner_opts](https://user-images.githubusercontent.com/17025244/101144438-00ca2300-3621-11eb-8dc3-604069aad644.png)

**Comment by tyanai** [comment]
Hi Oggy,

 

I checked and the feature is actually working as you expect.  

 

If all runs failed (all of them, not just one of them) – the build will be marked as failed ONLY if the total number of runs from ALL sessions is equals the total number of failures from all sessions.

 

If some runs failed, (and you want to mark the build as complete only if all runs passed), the build will be marked as failed, but all runs will be executed.

 

Thanks,

 

Tal.

**Comment by bigblondewolf** [comment]
Hi Tal,

Yes, it turns out the build continues. You may need to update the docs, the
explanation string states the opposite - that's why I didn't try in the
first place.

Thanks,
Oggy

На нд, 6.12.2020 г. в 13:04 ч. Tal Yanai <notifications@github.com> написа:

**Comment by tyanai** [comment]
Got it. I will close this one then.
